var canvas = document.getElementsByTagName("canvas")[0];
document.body.appendChild(canvas);
var ctx = canvas.getContext("2d");
ctx.strokeStyle = "rgb(255, 0, 0)";
ctx.lineWidth = 1;
var Xaxis = new Path2D();
Xaxis.rect(0, 0, 200, 0);
ctx.stroke(Xaxis);
ctx.strokeStyle = "rgb(0, 255, 0)";
var Yaxis = new Path2D();
Yaxis.rect(0, 0, 0, 200);
ctx.stroke(Yaxis);
var posX = 100;
var posY = 100;
var w = 100;
var h = 100;
// gradient
var gradient = ctx.createLinearGradient(0, posY, 0, posY + h);
gradient.addColorStop(0, "red");
gradient.addColorStop(1, "black");
var UwU = new Path2D();
UwU.roundRect(posX, posY, w, h, 5);
ctx.fillStyle = gradient;
ctx.fill(UwU);
ctx.rotate(20 * Math.PI / 180);
ctx.fill(UwU);
ctx.transform(1, 0.5, 0, 1, 0, 0);
ctx.fill(UwU);
